### ISSUE TITLE
The mod outputs garbage logs

### ISSUE THREAD

**Issue by HKLab** [homothetyhk/HollowKnight.BenchwarpMod#27]
https://github.com/homothetyhk/HollowKnight.BenchwarpMod/blob/7047c5b235f6e4281ce960e47e08f41140c6dc1e/Benchwarp/TopMenu.cs#L418
https://github.com/homothetyhk/HollowKnight.BenchwarpMod/blob/7047c5b235f6e4281ce960e47e08f41140c6dc1e/Benchwarp/TopMenu.cs#L428
https://github.com/homothetyhk/HollowKnight.BenchwarpMod/blob/7047c5b235f6e4281ce960e47e08f41140c6dc1e/Benchwarp/TopMenu.cs#L413

Using `HeroController.instance` to check for player presence will cause UnityLogger to output a lot of garbage, use `HeroController.UnsafeInstance` instead.The same is true for `GameManager.instance`.

**Comment by HKLab** [comment]
https://github.com/homothetyhk/HollowKnight.BenchwarpMod/blob/7047c5b235f6e4281ce960e47e08f41140c6dc1e/Benchwarp/CanvasUtil/CanvasButton.cs#L69-L71
`UnityEngine.Object.DontDestroyOnLoad` can only be used for root objects, otherwise it will output "DontDestroyOnLoad only works for root GameObjects or components on root GameObjects."

**Comment by homothetyhk** [comment]
Closed by #28.
