### ISSUE TITLE
Start warp doesn't heal the player if Joni's Blessing is equipped

### ISSUE THREAD

**Issue by Shoes4Clues** [homothetyhk/HollowKnight.BenchwarpMod#36]
If Joni's Blessing is equipped, start warp, unlike benches, sets the player to 1 health.

**Comment by homothetyhk** [comment]
Fixed in [5258ea7](https://github.com/homothetyhk/HollowKnight.BenchwarpMod/commit/5258ea710e48246484bdfa636496e7e0a32b3b16).
