### ISSUE TITLE
Softlock after bad custom-bench placement

### ISSUE THREAD

**Issue by MaxMagnos** [homothetyhk/HollowKnight.BenchwarpMod#37]
I have just managed to softlock my game. I deployed a bench in the Colosseum of Fools, in the "Main room" simply to  quickly change my charms before entering the fight. After closing the game and restarting it, when i try to load my savefile the camera will simply load into this room, slightly "wiggling" around but my character and the bench both don't spawn. I ALSO can't open the menu, no keys do anything so to leave i can only use Alt+F4. 

I suspect its simply that the game can't load a bench there and since there is no bench, the knight also doesn't spawn in and therefore i don't get control. Is there a way to fix this softlock? Maybe a way to change the "last bench rested at" in the savefile?

**Comment by homothetyhk** [comment]
The easiest way is to open the modded save file (i.e. user1.modded.json, etc) in a text editor, and navigate to the "atDeployedBench" field. Setting this to false should return you to your last permanent bench when you next load the game. You could also modify the nearby "benchX", "benchY", and "benchScene" settings to move the deployed bench back to a safe location, but that shouldn't be necessary.

**Comment by homothetyhk** [comment]
Actually, I forgot that no save editing is strictly required for this type of issue. If you disable Benchwarp from Options->Mods->Benchwarp Options->Benchwarp (or by removing the mod through the installer), then you will also respawn at your last permanent respawn point.
