### ISSUE TITLE
求Benchwarp的mod bug修复

### ISSUE THREAD

**Issue by 1211211234567** [homothetyhk/HollowKnight.BenchwarpMod#38]
把椅子放在愚人角斗场决斗 死亡或者退出 就会卡在里面 求修复！

**Comment by homothetyhk** [comment]
Addressed in ff32f74.

**Comment by Clazex** [comment]
Time to bring this up: Some people use Benchwarp to quickly navigate in HoG, however this requires turning off (previous) `No Dark or Dream Rooms`.

Suggestion: Remove this line 
https://github.com/homothetyhk/HollowKnight.BenchwarpMod/blob/ff32f747c018b939b75fe9dc224fb7275e2ae6b3/Benchwarp/BenchMaker.cs#L121
and use
```csharp
BossSceneController.IsBossScene
```
to detect Godhome boss room deployments (this covers the Godseeker rooms in pantheons as well).

**Comment by homothetyhk** [comment]
Thanks, this has been addressed with [acd51ab](https://github.com/homothetyhk/HollowKnight.BenchwarpMod/commit/acd51ab7023e158099e1ee39af7519021c257ae1).
